a = int(input("a ="))
milliart = a // 1000000000
yuzmillion = a % 100000000//1000000
onmillion = a % 1000000 // 100000
million = a // 1000000
yuzming = a % 1000000//100000
onming = a % 100000//10000
ming = a % 10000 // 1000
yuz =  a % 1000 // 100
onlik = a % 100 // 10
birlik = a % 10
if milliart ==1: print("Bir million",end=" ")
if milliart ==2: print("Ikki million",end=" ")
if milliart ==3: print("Uch million",end=" ")
if milliart ==4: print("To'rt million",end=" ")
if milliart ==5: print("Besh million",end=" ")
if milliart ==6: print("Olti million",end=" ")
if milliart ==7: print("Yetti million",end=" ")
if milliart ==8: print("Sakkiz million",end=" ")
if milliart ==9: print("To'qqiz million",end=" ")

if yuzming == 1: print("Bir yuz", end=" ")
if yuzming == 2: print("Ikki yuz", end=" ")
if yuzming == 3: print("Uch yuz", end=" ")
if yuzming == 4: print("To'rt yuz", end=" ")
if yuzming == 5: print("Besh yuz", end=" ")
if yuzming == 6: print("Olti yuz", end=" ")
if yuzming == 7:print("Yetti yuz", end=" ")
if yuzming == 8: print("Sakkiz yuz", end=" ")
if yuzming == 9: print("To'qqiz yuz", end=" ")

if onming ==1: print("O'n",end=" ")
if onming ==2: print("Yigirma",end=" ")
if onming ==3: print("O'ttiz",end=" ")
if onming ==4: print("Qiriq",end=" ")
if onming ==5: print("Ellik",end=" ")
if onming ==6: print("Oltmish",end=" ")
if onming ==7: print("Yetmish",end=" ")
if onming ==8: print("Sakson",end=" ")
if onming ==9: print("To'qson",end=" ")

if million ==1: print("Bir million",end=" ")
if million ==2: print("Ikki million",end=" ")
if million ==3: print("Uch million",end=" ")
if million ==4: print("To'rt million",end=" ")
if million ==5: print("Besh million",end=" ")
if million ==6: print("Olti million",end=" ")
if million ==7: print("Yetti million",end=" ")
if million ==8: print("Sakkiz million",end=" ")
if million ==9: print("To'qqiz million",end=" ")

if yuzming == 1: print("Bir yuz", end=" ")
if yuzming == 2: print("Ikki yuz", end=" ")
if yuzming == 3: print("Uch yuz", end=" ")
if yuzming == 4: print("To'rt yuz", end=" ")
if yuzming == 5: print("Besh yuz", end=" ")
if yuzming == 6: print("Olti yuz", end=" ")
if yuzming == 7:print("Yetti yuz", end=" ")
if yuzming == 8: print("Sakkiz yuz", end=" ")
if yuzming == 9: print("To'qqiz yuz", end=" ")

if onming ==1: print("O'n",end=" ")
if onming ==2: print("Yigirma",end=" ")
if onming ==3: print("O'ttiz",end=" ")
if onming ==4: print("Qiriq",end=" ")
if onming ==5: print("Ellik",end=" ")
if onming ==6: print("Oltmish",end=" ")
if onming ==7: print("Yetmish",end=" ")
if onming ==8: print("Sakson",end=" ")
if onming ==9: print("To'qson",end=" ")

if ming == 1: print("Bir", end=" ")
if ming == 2: print("Ikki", end=" ")
if ming == 3: print("Uch", end=" ")
if ming == 4: print("To'rt", end=" ")
if ming == 5: print("Besh", end=" ")
if ming == 6: print("Olti", end=" ")
if ming == 7: print("Yetti", end=" ")
if ming == 8: print("Sakkiz", end=" ")
if ming == 9: print("To'qqiz", end=" ")
if  yuzming >0 or onming>0 or ming>0:
    print("ming",end=" ")

if yuz ==1 : print("Bir yuz",end=" ")
if yuz ==2 : print("Ikki yuz",end=" ")
if yuz ==3 : print("Uch yuz",end=" ")
if yuz ==4:  print("To'rt yuz",end=" ")
if  yuz ==5: print("Besh yuz",end=" ")
if  yuz ==6: print("Olti yuz",end=" ")
if yuz ==7:  print("Yetti yuz",end=" ")
if yuz ==8:  print("Sakkiz yuz",end=" ")
if yuz ==9:  print("To'qqiz yuz",end=" ")

if onlik == 1: print("O'n", end=" ")
if  onlik == 2: print("Yigirma", end=" ")
if onlik == 3: print("O'ttiz", end=" ")
if onlik == 4: print("Qiriq", end=" ")
if onlik == 5: print("Ellik", end=" ")
if onlik == 6: print("Olmish", end=" ")
if onlik == 7: print("Yetmish", end=" ")
if onlik == 8: print("Sakson", end=" ")
if onlik == 9: print("To'qson", end=" ")

if birlik == 1: print("Bir")
if  birlik == 2: print("Ikki")
if birlik == 3: print("Uch")
if birlik == 4: print("To'rt")
if birlik == 5: print("Besh")
if birlik == 6: print("Olti")
if birlik == 7: print("Yetti")
if birlik == 8: print("Sakkiz")
if birlik == 9: print("To'qqiz")

if a ==0: print("No'l")